const createGroupMeApi = require("../services/GroupMeApi");
const Groups = require("../../../groups");
const Users = require("../../../users");
const { to } = require("../../../helpers");

/*
* Handle an admin message generated by GroupMe
*/

const handleGroupMeAutomatedMessage = async (req, res, next) => {
  console.log("GRPUPS", Groups);
  try {
    if (req.body.text.includes("added") || req.body.text.includes("rejoined")) {
      const GroupMeApi = createGroupMeApi(process.env.GROUPME_ACCESS_TOKEN);

      // get info on the groupme group that received the message
      let err, groupMeGroup;
      [err, groupMeGroup] = await to(GroupMeApi.getGroup(req.body.group_id));
      if (err) next(err);

      // if nothing went wrong fetching the group info
      if (groupMeGroup) {
        let group;
        [err, group] = await to(Groups.getGroup(groupMeGroup.group_id));
        if (err) next(err);

        const members = groupMeGroup.members;
        let updatedMembers = [];
        let hasNewMember = false;

        // check if groupme members are MM users
        for (let member of members) {
          let err, user;
          [err, user] = await to(Users.findOrCreateUser(member, group._id));
          if (err) next(err);

          updatedMembers.push(user._id);

          // if user id isn't in group members, add it
          if (group.members.indexOf(user._id) < 0) {
            hasNewMember = true;
            // await to(GroupController._addUserToGroup(user._id, group._id));
            await GroupMeApi.sendBotMessage(`Welcome ${user.name} 👋`);
          }
        }

        // send some helper text if there are any new members
        if (hasNewMember) {
          await GroupMeApi.sendBotMessage(
            `Learn how to play and manage your predictions at ${
              process.env.CLIENT_URL
            }`
          );
        }

        group.members = updatedMembers;
        await group.save();
      }
    } else {
      res.json({ message: "No op" });
    }
  } catch (e) {
    next(e);
  }
};

module.exports = handleGroupMeAutomatedMessage;
