const { to } = require("../../../helpers");

// GroupMe Services
const handleGroupMeAutomatedMessage = require("../controllers/handleGroupMeAutomatedMessage");
const sendGroupRankings = require("../controllers/sendGroupRankings");
const handleUserPrediction = require("../controllers/handleUserPrediction");

/* Receive a message from GroupMe */
exports.receiveMessage = async (req, res, next) => {
  console.log("RECEIVED", req.body);
  // if it's a GroupMe automated message
  if (req.body.sender_type === "bot") {
    return null;
  }

  // extract message from POST body
  const text = req.body.text;

  // send off into applicable controller
  if (req.body.user_id === "0") {
    // this message was generated by GroupMe, handle accordingly
    await to(handleGroupMeAutomatedMessage(req, res, next));
  } else if (
    text.toLowerCase().includes("ranking?") ||
    text.toLowerCase().includes("rankings?")
  ) {
    // send rankings to the group
    await to(sendGroupRankings(req, res, next));
  } else if (text.includes("=") || text.includes("-")) {
    await to(handleUserPrediction(req, res, next));
  }
};
