const { Lib } = require("../../../index");

module.exports = async (req, res, next) => {
  // if it's a GroupMe automated message
  if (req.body.sender_type === "bot") {
    return null;
  }

  // extract message from POST body
  const text = req.body.text;

  // send off into applicable controller
  if (req.body.user_id === "0") {
    // this message was generated by GroupMe, handle accordingly
    await Lib.handleGroupMeAutomatedMessage(req);
    res.json({ message: "No op" });
  } else if (
    text.toLowerCase().includes("ranking?") ||
    text.toLowerCase().includes("rankings?")
  ) {
    // send rankings to the group
    await Lib.sendGroupRankings(req.body.group_id);
    res.json({ message: "No op" });
  } else if (text.includes("=") || text.includes("-")) {
    await Lib.handleUserPrediction(req);
    res.json({ message: "No op" });
  }
};
