const { Lib } = require("../../../index");

module.exports = async reqBody => {
  // extract message from POST body
  const { text, user_id } = reqBody;

  // send off into applicable controller
  if (user_id === "0") {
    // this message was generated by GroupMe, handle accordingly
    await Lib.handleGroupMeAutomatedMessage(req);
    res.json({ message: "No op" });
  } else if (
    text.toLowerCase().includes("ranking?") ||
    text.toLowerCase().includes("rankings?")
  ) {
    // send rankings to the group
    await Lib.sendGroupRankings(req.body.group_id);
    res.json({ message: "No op" });
  } else if (text.includes("=") || text.includes("-")) {
    await Lib.handleUserPrediction(req);
    res.json({ message: "No op" });
  }
};
